language: go
sudo: required
dist: trusty
go: "1.12"

services:
- docker

install: true
script:
  - sudo cp ./cluster/dind-cluster/kubectl /usr/bin/kubectl
  - make test
  - make deploy-test-cluster
  - KUBECONFIG="`pwd`/cluster/dind-cluster/config" go test -timeout 30m -v -race ./tests/...

deploy:
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io && make docker-build docker-push
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io && make docker-build docker-push IMAGE_TAG=$TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
