apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: kubemacpool-system
  labels:
    control-plane: mac-controller-manager
    prometheus.kubemacpool.io: "true"
spec:
  selector:
    control-plane: mac-controller-manager
  ports:
    - name: metrics
      port: 8443
      targetPort: 8443
      protocol: TCP
